version: '3.9'

services:

  _build: &image
    build:
      context: .
      dockerfile: Dockerfile.dev
 
  web: 
    <<: *image
    command: ./script/start
    tty: true
    volumes: 
      - .:/code
      - bundler:/user/local/bundle
    ports: 
      - 3000:3000
    environment: 
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=unbreakable
    depends_on:
      - db
      
  db: 
    image: postgres:14
    volumes: 
      - db-data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=unbreakable
volumes:
  db-data:
  bundler:
